- name: Build minimal Podman image
  hosts: localhost
  gather_facts: false

  vars:
    image_name: "ansible-alpine"
    dockerfile_path: "."

  tasks:
    - name: Build Podman image
      community.general.podman_image:
        name: "{{ image_name }}"
        build:
          path: "{{ dockerfile_path }}"