---
- name: Build minimal Ansible Docker image
  hosts: localhost
  become: true

  vars:
    image_name: "ansible-alpine"

  tasks:
    - name: Build Docker image
      community.docker.docker_image:
        source: build
        build:
          path: "."
          dockerfile: "Dockerfile"
        name: "{{ image_name }}"